version: '3'

services:
  app:
    container_name: purity-app
    build: .
    volumes: 
      - './src:/usr/src/purity_app/src'
    ports:
      - 3000:3000
    links: 
      - mongo
    depends_on: 
    - mongo
  mongo:
    container_name: purity-db
    image: mongo:latest
    volumes: 
      - './data:/data/db'
    ports:
     - 27017:27017   
volumes: 
  data: